import type { editor } from 'monaco-editor'

export interface Theme {
  id: string
  name: string
  type: 'dark' | 'light'
  author: string
  tags: string[]
  previewColors: string[]
  colors: Record<string, string> // CSS variable name -> value
  monacoTheme: string // Monaco editor theme name
  /** Optional custom Monaco theme definition. When provided the theme store will register it. */
  monacoThemeData?: editor.IStandaloneThemeData
}

// ---------------------------------------------------------------------------
// Helper to build a Monaco IStandaloneThemeData with the common token rules
// ---------------------------------------------------------------------------
function monacoThemeData(
  base: 'vs' | 'vs-dark',
  bg: string,
  fg: string,
  syntax: {
    strings: string
    keywords: string
    functions: string
    types: string
    comments: string
    numbers?: string
    operators?: string
    variables?: string
  },
  editorColors: Partial<Record<string, string>> = {},
): editor.IStandaloneThemeData {
  return {
    base,
    inherit: true,
    rules: [
      { token: '', foreground: fg.replace('#', '') },
      { token: 'comment', foreground: syntax.comments.replace('#', ''), fontStyle: 'italic' },
      { token: 'keyword', foreground: syntax.keywords.replace('#', '') },
      { token: 'keyword.control', foreground: syntax.keywords.replace('#', '') },
      { token: 'keyword.operator', foreground: (syntax.operators || syntax.keywords).replace('#', '') },
      { token: 'string', foreground: syntax.strings.replace('#', '') },
      { token: 'string.escape', foreground: syntax.strings.replace('#', '') },
      { token: 'number', foreground: (syntax.numbers || syntax.types).replace('#', '') },
      { token: 'type', foreground: syntax.types.replace('#', '') },
      { token: 'type.identifier', foreground: syntax.types.replace('#', '') },
      { token: 'class', foreground: syntax.types.replace('#', '') },
      { token: 'interface', foreground: syntax.types.replace('#', '') },
      { token: 'enum', foreground: syntax.types.replace('#', '') },
      { token: 'function', foreground: syntax.functions.replace('#', '') },
      { token: 'function.declaration', foreground: syntax.functions.replace('#', '') },
      { token: 'variable', foreground: (syntax.variables || fg).replace('#', '') },
      { token: 'variable.predefined', foreground: syntax.types.replace('#', '') },
      { token: 'constant', foreground: (syntax.numbers || syntax.types).replace('#', '') },
      { token: 'tag', foreground: syntax.keywords.replace('#', '') },
      { token: 'attribute.name', foreground: syntax.functions.replace('#', '') },
      { token: 'attribute.value', foreground: syntax.strings.replace('#', '') },
      { token: 'delimiter', foreground: fg.replace('#', '') },
      { token: 'operator', foreground: (syntax.operators || syntax.keywords).replace('#', '') },
      { token: 'regexp', foreground: syntax.strings.replace('#', '') },
      { token: 'annotation', foreground: syntax.types.replace('#', '') },
      { token: 'metatag', foreground: syntax.keywords.replace('#', '') },
    ],
    colors: {
      'editor.background': bg,
      'editor.foreground': fg,
      ...editorColors,
    },
  }
}

export const themes: Theme[] = [
  // ---------- Orion Dark (current default) ----------
  {
    id: 'orion-dark',
    name: 'Orion Dark',
    type: 'dark',
    author: 'Orion IDE',
    tags: ['dark', 'default', 'modern'],
    previewColors: ['#0d1117', '#e6edf3', '#58a6ff', '#3fb950', '#f85149', '#bc8cff'],
    monacoTheme: 'vs-dark',
    colors: {
      '--bg-primary': '#0d1117',
      '--bg-secondary': '#161b22',
      '--bg-tertiary': '#010409',
      '--bg-hover': '#1c2128',
      '--bg-active': '#252c35',
      '--bg-elevated': '#1c2128',
      '--border': '#21262d',
      '--border-bright': '#30363d',
      '--border-focus': '#58a6ff',
      '--text-primary': '#e6edf3',
      '--text-secondary': '#8b949e',
      '--text-muted': '#484f58',
      '--accent': '#58a6ff',
      '--accent-blue': '#58a6ff',
      '--accent-green': '#3fb950',
      '--accent-orange': '#f78166',
      '--accent-red': '#f85149',
      '--accent-purple': '#bc8cff',
      '--accent-yellow': '#e3b341',
      '--accent-cyan': '#76e3ea',
      '--scrollbar-thumb': '#484f58',
      '--scrollbar-track': '#0d1117',
    },
  },

  // ---------- Orion Darker (higher contrast) ----------
  {
    id: 'orion-darker',
    name: 'Orion Darker',
    type: 'dark',
    author: 'Orion IDE',
    tags: ['dark', 'high-contrast', 'modern'],
    previewColors: ['#000000', '#f0f4fc', '#6cb6ff', '#56d364', '#ff6b61', '#d2a8ff'],
    monacoTheme: 'vs-dark',
    colors: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#0a0a0f',
      '--bg-tertiary': '#000000',
      '--bg-hover': '#111118',
      '--bg-active': '#1a1a24',
      '--bg-elevated': '#111118',
      '--border': '#1a1a24',
      '--border-bright': '#2a2a38',
      '--border-focus': '#6cb6ff',
      '--text-primary': '#f0f4fc',
      '--text-secondary': '#9da8b7',
      '--text-muted': '#505868',
      '--accent': '#6cb6ff',
      '--accent-blue': '#6cb6ff',
      '--accent-green': '#56d364',
      '--accent-orange': '#ffa070',
      '--accent-red': '#ff6b61',
      '--accent-purple': '#d2a8ff',
      '--accent-yellow': '#f0d050',
      '--accent-cyan': '#8cf0f8',
      '--scrollbar-thumb': '#505868',
      '--scrollbar-track': '#000000',
    },
  },

  // ---------- GitHub Dark ----------
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    type: 'dark',
    author: 'GitHub',
    tags: ['dark', 'popular', 'github'],
    previewColors: ['#0d1117', '#c9d1d9', '#58a6ff', '#3fb950', '#f85149', '#bc8cff'],
    monacoTheme: 'github-dark',
    monacoThemeData: monacoThemeData('vs-dark', '#0d1117', '#c9d1d9', {
      strings: '#a5d6ff',
      keywords: '#ff7b72',
      functions: '#d2a8ff',
      types: '#79c0ff',
      comments: '#8b949e',
      numbers: '#79c0ff',
      operators: '#ff7b72',
      variables: '#ffa657',
    }, {
      'editor.selectionBackground': '#264f78',
      'editor.lineHighlightBackground': '#161b22',
      'editorLineNumber.foreground': '#484f58',
      'editorCursor.foreground': '#c9d1d9',
    }),
    colors: {
      '--bg-primary': '#0d1117',
      '--bg-secondary': '#010409',
      '--bg-tertiary': '#010409',
      '--bg-hover': '#1f242c',
      '--bg-active': '#292e36',
      '--bg-elevated': '#1c2128',
      '--border': '#30363d',
      '--border-bright': '#484f58',
      '--border-focus': '#1f6feb',
      '--text-primary': '#c9d1d9',
      '--text-secondary': '#8b949e',
      '--text-muted': '#484f58',
      '--accent': '#58a6ff',
      '--accent-blue': '#58a6ff',
      '--accent-green': '#3fb950',
      '--accent-orange': '#d29922',
      '--accent-red': '#f85149',
      '--accent-purple': '#bc8cff',
      '--accent-yellow': '#d29922',
      '--accent-cyan': '#39d353',
      '--scrollbar-thumb': '#484f58',
      '--scrollbar-track': '#0d1117',
    },
  },

  // ---------- GitHub Light ----------
  {
    id: 'github-light',
    name: 'GitHub Light',
    type: 'light',
    author: 'GitHub',
    tags: ['light', 'popular', 'github'],
    previewColors: ['#ffffff', '#24292f', '#0969da', '#1a7f37', '#cf222e', '#8250df'],
    monacoTheme: 'github-light',
    monacoThemeData: monacoThemeData('vs', '#ffffff', '#24292f', {
      strings: '#0a3069',
      keywords: '#cf222e',
      functions: '#8250df',
      types: '#0550ae',
      comments: '#6e7781',
      numbers: '#0550ae',
      operators: '#cf222e',
      variables: '#953800',
    }, {
      'editor.selectionBackground': '#add6ff',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editorLineNumber.foreground': '#8c959f',
      'editorCursor.foreground': '#24292f',
    }),
    colors: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f6f8fa',
      '--bg-tertiary': '#f6f8fa',
      '--bg-hover': '#eaeef2',
      '--bg-active': '#dce2e8',
      '--bg-elevated': '#ffffff',
      '--border': '#d0d7de',
      '--border-bright': '#afb8c1',
      '--border-focus': '#0969da',
      '--text-primary': '#24292f',
      '--text-secondary': '#57606a',
      '--text-muted': '#6e7781',
      '--accent': '#0969da',
      '--accent-blue': '#0969da',
      '--accent-green': '#1a7f37',
      '--accent-orange': '#9a6700',
      '--accent-red': '#cf222e',
      '--accent-purple': '#8250df',
      '--accent-yellow': '#9a6700',
      '--accent-cyan': '#0550ae',
      '--scrollbar-thumb': '#afb8c1',
      '--scrollbar-track': '#ffffff',
    },
  },

  // ---------- Solarized Dark ----------
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    author: 'Ethan Schoonover',
    tags: ['dark', 'classic', 'warm', 'low-contrast'],
    previewColors: ['#002b36', '#839496', '#268bd2', '#859900', '#dc322f', '#2aa198'],
    monacoTheme: 'solarized-dark',
    monacoThemeData: monacoThemeData('vs-dark', '#002b36', '#839496', {
      strings: '#2aa198',
      keywords: '#859900',
      functions: '#268bd2',
      types: '#b58900',
      comments: '#586e75',
      numbers: '#d33682',
      operators: '#859900',
      variables: '#839496',
    }, {
      'editor.selectionBackground': '#073642',
      'editor.lineHighlightBackground': '#073642',
      'editorLineNumber.foreground': '#586e75',
      'editorCursor.foreground': '#839496',
    }),
    colors: {
      '--bg-primary': '#002b36',
      '--bg-secondary': '#00212b',
      '--bg-tertiary': '#00212b',
      '--bg-hover': '#073642',
      '--bg-active': '#0a4050',
      '--bg-elevated': '#073642',
      '--border': '#073642',
      '--border-bright': '#586e75',
      '--border-focus': '#268bd2',
      '--text-primary': '#839496',
      '--text-secondary': '#657b83',
      '--text-muted': '#586e75',
      '--accent': '#268bd2',
      '--accent-blue': '#268bd2',
      '--accent-green': '#859900',
      '--accent-orange': '#cb4b16',
      '--accent-red': '#dc322f',
      '--accent-purple': '#6c71c4',
      '--accent-yellow': '#b58900',
      '--accent-cyan': '#2aa198',
      '--scrollbar-thumb': '#586e75',
      '--scrollbar-track': '#002b36',
    },
  },

  // ---------- Solarized Light ----------
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    type: 'light',
    author: 'Ethan Schoonover',
    tags: ['light', 'classic', 'warm', 'low-contrast'],
    previewColors: ['#fdf6e3', '#657b83', '#268bd2', '#859900', '#dc322f', '#2aa198'],
    monacoTheme: 'solarized-light',
    monacoThemeData: monacoThemeData('vs', '#fdf6e3', '#657b83', {
      strings: '#2aa198',
      keywords: '#859900',
      functions: '#268bd2',
      types: '#b58900',
      comments: '#93a1a1',
      numbers: '#d33682',
      operators: '#859900',
      variables: '#657b83',
    }, {
      'editor.selectionBackground': '#eee8d5',
      'editor.lineHighlightBackground': '#eee8d5',
      'editorLineNumber.foreground': '#93a1a1',
      'editorCursor.foreground': '#657b83',
    }),
    colors: {
      '--bg-primary': '#fdf6e3',
      '--bg-secondary': '#eee8d5',
      '--bg-tertiary': '#eee8d5',
      '--bg-hover': '#e6dfcc',
      '--bg-active': '#ded7c4',
      '--bg-elevated': '#fdf6e3',
      '--border': '#d6cab9',
      '--border-bright': '#93a1a1',
      '--border-focus': '#268bd2',
      '--text-primary': '#657b83',
      '--text-secondary': '#586e75',
      '--text-muted': '#93a1a1',
      '--accent': '#268bd2',
      '--accent-blue': '#268bd2',
      '--accent-green': '#859900',
      '--accent-orange': '#cb4b16',
      '--accent-red': '#dc322f',
      '--accent-purple': '#6c71c4',
      '--accent-yellow': '#b58900',
      '--accent-cyan': '#2aa198',
      '--scrollbar-thumb': '#93a1a1',
      '--scrollbar-track': '#fdf6e3',
    },
  },

  // ---------- Tokyo Night ----------
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    type: 'dark',
    author: 'enkia',
    tags: ['dark', 'popular', 'modern', 'cool'],
    previewColors: ['#1a1b26', '#a9b1d6', '#7aa2f7', '#9ece6a', '#f7768e', '#bb9af7'],
    monacoTheme: 'tokyo-night',
    monacoThemeData: monacoThemeData('vs-dark', '#1a1b26', '#a9b1d6', {
      strings: '#9ece6a',
      keywords: '#bb9af7',
      functions: '#7aa2f7',
      types: '#2ac3de',
      comments: '#565f89',
      numbers: '#ff9e64',
      operators: '#89ddff',
      variables: '#c0caf5',
    }, {
      'editor.selectionBackground': '#28293d',
      'editor.lineHighlightBackground': '#1e1f2e',
      'editorLineNumber.foreground': '#3b3d57',
      'editorCursor.foreground': '#c0caf5',
    }),
    colors: {
      '--bg-primary': '#1a1b26',
      '--bg-secondary': '#16161e',
      '--bg-tertiary': '#16161e',
      '--bg-hover': '#24253a',
      '--bg-active': '#2e2f48',
      '--bg-elevated': '#1e1f2e',
      '--border': '#292e42',
      '--border-bright': '#3b3d57',
      '--border-focus': '#7aa2f7',
      '--text-primary': '#a9b1d6',
      '--text-secondary': '#787c99',
      '--text-muted': '#565f89',
      '--accent': '#7aa2f7',
      '--accent-blue': '#7aa2f7',
      '--accent-green': '#9ece6a',
      '--accent-orange': '#ff9e64',
      '--accent-red': '#f7768e',
      '--accent-purple': '#bb9af7',
      '--accent-yellow': '#e0af68',
      '--accent-cyan': '#2ac3de',
      '--scrollbar-thumb': '#3b3d57',
      '--scrollbar-track': '#1a1b26',
    },
  },

  // ---------- Catppuccin Mocha ----------
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    type: 'dark',
    author: 'Catppuccin',
    tags: ['dark', 'popular', 'pastel', 'warm'],
    previewColors: ['#1e1e2e', '#cdd6f4', '#89b4fa', '#a6e3a1', '#f38ba8', '#cba6f7'],
    monacoTheme: 'catppuccin-mocha',
    monacoThemeData: monacoThemeData('vs-dark', '#1e1e2e', '#cdd6f4', {
      strings: '#a6e3a1',
      keywords: '#cba6f7',
      functions: '#89b4fa',
      types: '#89dceb',
      comments: '#6c7086',
      numbers: '#fab387',
      operators: '#89dceb',
      variables: '#cdd6f4',
    }, {
      'editor.selectionBackground': '#313244',
      'editor.lineHighlightBackground': '#232334',
      'editorLineNumber.foreground': '#45475a',
      'editorCursor.foreground': '#f5e0dc',
    }),
    colors: {
      '--bg-primary': '#1e1e2e',
      '--bg-secondary': '#181825',
      '--bg-tertiary': '#181825',
      '--bg-hover': '#28283d',
      '--bg-active': '#313244',
      '--bg-elevated': '#232334',
      '--border': '#313244',
      '--border-bright': '#45475a',
      '--border-focus': '#89b4fa',
      '--text-primary': '#cdd6f4',
      '--text-secondary': '#a6adc8',
      '--text-muted': '#6c7086',
      '--accent': '#89b4fa',
      '--accent-blue': '#89b4fa',
      '--accent-green': '#a6e3a1',
      '--accent-orange': '#fab387',
      '--accent-red': '#f38ba8',
      '--accent-purple': '#cba6f7',
      '--accent-yellow': '#f9e2af',
      '--accent-cyan': '#89dceb',
      '--scrollbar-thumb': '#45475a',
      '--scrollbar-track': '#1e1e2e',
    },
  },

  // ---------- Monokai Pro ----------
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    type: 'dark',
    author: 'Monokai',
    tags: ['dark', 'classic', 'popular', 'vibrant'],
    previewColors: ['#2d2a2e', '#fcfcfa', '#ffd866', '#a9dc76', '#ff6188', '#ab9df2'],
    monacoTheme: 'monokai-pro',
    monacoThemeData: monacoThemeData('vs-dark', '#2d2a2e', '#fcfcfa', {
      strings: '#ffd866',
      keywords: '#ff6188',
      functions: '#a9dc76',
      types: '#78dce8',
      comments: '#727072',
      numbers: '#ab9df2',
      operators: '#ff6188',
      variables: '#fcfcfa',
    }, {
      'editor.selectionBackground': '#403e41',
      'editor.lineHighlightBackground': '#363337',
      'editorLineNumber.foreground': '#5b585f',
      'editorCursor.foreground': '#fcfcfa',
    }),
    colors: {
      '--bg-primary': '#2d2a2e',
      '--bg-secondary': '#221f22',
      '--bg-tertiary': '#403e41',
      '--bg-hover': '#403e41',
      '--bg-active': '#4a474b',
      '--bg-elevated': '#403e41',
      '--border': '#49474a',
      '--border-bright': '#5b585f',
      '--border-focus': '#ffd866',
      '--text-primary': '#fcfcfa',
      '--text-secondary': '#c1c0c0',
      '--text-muted': '#727072',
      '--accent': '#ffd866',
      '--accent-blue': '#78dce8',
      '--accent-green': '#a9dc76',
      '--accent-orange': '#fc9867',
      '--accent-red': '#ff6188',
      '--accent-purple': '#ab9df2',
      '--accent-yellow': '#ffd866',
      '--accent-cyan': '#78dce8',
      '--scrollbar-thumb': '#5b585f',
      '--scrollbar-track': '#2d2a2e',
    },
  },

  // ---------- Dracula ----------
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    author: 'Zeno Rocha',
    tags: ['dark', 'popular', 'vibrant', 'cool'],
    previewColors: ['#282a36', '#f8f8f2', '#bd93f9', '#50fa7b', '#ff5555', '#ffb86c'],
    monacoTheme: 'dracula',
    monacoThemeData: monacoThemeData('vs-dark', '#282a36', '#f8f8f2', {
      strings: '#f1fa8c',
      keywords: '#ff79c6',
      functions: '#50fa7b',
      types: '#8be9fd',
      comments: '#6272a4',
      numbers: '#bd93f9',
      operators: '#ff79c6',
      variables: '#f8f8f2',
    }, {
      'editor.selectionBackground': '#44475a',
      'editor.lineHighlightBackground': '#2c2e3a',
      'editorLineNumber.foreground': '#6272a4',
      'editorCursor.foreground': '#f8f8f2',
    }),
    colors: {
      '--bg-primary': '#282a36',
      '--bg-secondary': '#21222c',
      '--bg-tertiary': '#343746',
      '--bg-hover': '#343746',
      '--bg-active': '#44475a',
      '--bg-elevated': '#343746',
      '--border': '#44475a',
      '--border-bright': '#6272a4',
      '--border-focus': '#bd93f9',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#c0c0c0',
      '--text-muted': '#6272a4',
      '--accent': '#bd93f9',
      '--accent-blue': '#8be9fd',
      '--accent-green': '#50fa7b',
      '--accent-orange': '#ffb86c',
      '--accent-red': '#ff5555',
      '--accent-purple': '#bd93f9',
      '--accent-yellow': '#f1fa8c',
      '--accent-cyan': '#8be9fd',
      '--scrollbar-thumb': '#6272a4',
      '--scrollbar-track': '#282a36',
    },
  },

  // ---------- One Dark Pro ----------
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    type: 'dark',
    author: 'binaryify',
    tags: ['dark', 'popular', 'atom', 'balanced'],
    previewColors: ['#282c34', '#abb2bf', '#61afef', '#98c379', '#e06c75', '#c678dd'],
    monacoTheme: 'one-dark-pro',
    monacoThemeData: monacoThemeData('vs-dark', '#282c34', '#abb2bf', {
      strings: '#98c379',
      keywords: '#c678dd',
      functions: '#61afef',
      types: '#e5c07b',
      comments: '#5c6370',
      numbers: '#d19a66',
      operators: '#56b6c2',
      variables: '#e06c75',
    }, {
      'editor.selectionBackground': '#3e4452',
      'editor.lineHighlightBackground': '#2c313a',
      'editorLineNumber.foreground': '#495162',
      'editorCursor.foreground': '#528bff',
    }),
    colors: {
      '--bg-primary': '#282c34',
      '--bg-secondary': '#21252b',
      '--bg-tertiary': '#2c313a',
      '--bg-hover': '#2c313a',
      '--bg-active': '#3e4452',
      '--bg-elevated': '#2c313a',
      '--border': '#3e4452',
      '--border-bright': '#5c6370',
      '--border-focus': '#61afef',
      '--text-primary': '#abb2bf',
      '--text-secondary': '#9da5b4',
      '--text-muted': '#5c6370',
      '--accent': '#61afef',
      '--accent-blue': '#61afef',
      '--accent-green': '#98c379',
      '--accent-orange': '#d19a66',
      '--accent-red': '#e06c75',
      '--accent-purple': '#c678dd',
      '--accent-yellow': '#e5c07b',
      '--accent-cyan': '#56b6c2',
      '--scrollbar-thumb': '#5c6370',
      '--scrollbar-track': '#282c34',
    },
  },

  // ---------- Nord ----------
  {
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    author: 'Arctic Ice Studio',
    tags: ['dark', 'popular', 'cool', 'arctic', 'muted'],
    previewColors: ['#2e3440', '#d8dee9', '#88c0d0', '#a3be8c', '#bf616a', '#b48ead'],
    monacoTheme: 'nord',
    monacoThemeData: monacoThemeData('vs-dark', '#2e3440', '#d8dee9', {
      strings: '#a3be8c',
      keywords: '#81a1c1',
      functions: '#88c0d0',
      types: '#8fbcbb',
      comments: '#616e88',
      numbers: '#b48ead',
      operators: '#81a1c1',
      variables: '#d8dee9',
    }, {
      'editor.selectionBackground': '#434c5e',
      'editor.lineHighlightBackground': '#3b4252',
      'editorLineNumber.foreground': '#4c566a',
      'editorCursor.foreground': '#d8dee9',
    }),
    colors: {
      '--bg-primary': '#2e3440',
      '--bg-secondary': '#292e39',
      '--bg-tertiary': '#3b4252',
      '--bg-hover': '#434c5e',
      '--bg-active': '#4c566a',
      '--bg-elevated': '#434c5e',
      '--border': '#3b4252',
      '--border-bright': '#4c566a',
      '--border-focus': '#88c0d0',
      '--text-primary': '#d8dee9',
      '--text-secondary': '#b8c5d9',
      '--text-muted': '#616e88',
      '--accent': '#88c0d0',
      '--accent-blue': '#81a1c1',
      '--accent-green': '#a3be8c',
      '--accent-orange': '#d08770',
      '--accent-red': '#bf616a',
      '--accent-purple': '#b48ead',
      '--accent-yellow': '#ebcb8b',
      '--accent-cyan': '#8fbcbb',
      '--scrollbar-thumb': '#4c566a',
      '--scrollbar-track': '#2e3440',
    },
  },

  // ---------- Gruvbox Dark ----------
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    type: 'dark',
    author: 'morhetz',
    tags: ['dark', 'popular', 'retro', 'warm', 'earthy'],
    previewColors: ['#282828', '#ebdbb2', '#458588', '#b8bb26', '#cc241d', '#d3869b'],
    monacoTheme: 'gruvbox-dark',
    monacoThemeData: monacoThemeData('vs-dark', '#282828', '#ebdbb2', {
      strings: '#b8bb26',
      keywords: '#fb4934',
      functions: '#fabd2f',
      types: '#83a598',
      comments: '#928374',
      numbers: '#d3869b',
      operators: '#fe8019',
      variables: '#ebdbb2',
    }, {
      'editor.selectionBackground': '#3c3836',
      'editor.lineHighlightBackground': '#32302f',
      'editorLineNumber.foreground': '#665c54',
      'editorCursor.foreground': '#ebdbb2',
    }),
    colors: {
      '--bg-primary': '#282828',
      '--bg-secondary': '#1d2021',
      '--bg-tertiary': '#32302f',
      '--bg-hover': '#3c3836',
      '--bg-active': '#504945',
      '--bg-elevated': '#3c3836',
      '--border': '#3c3836',
      '--border-bright': '#665c54',
      '--border-focus': '#458588',
      '--text-primary': '#ebdbb2',
      '--text-secondary': '#d5c4a1',
      '--text-muted': '#928374',
      '--accent': '#458588',
      '--accent-blue': '#83a598',
      '--accent-green': '#b8bb26',
      '--accent-orange': '#fe8019',
      '--accent-red': '#fb4934',
      '--accent-purple': '#d3869b',
      '--accent-yellow': '#fabd2f',
      '--accent-cyan': '#8ec07c',
      '--scrollbar-thumb': '#665c54',
      '--scrollbar-track': '#282828',
    },
  },

  // ---------- Gruvbox Light ----------
  {
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    type: 'light',
    author: 'morhetz',
    tags: ['light', 'retro', 'warm', 'earthy'],
    previewColors: ['#fbf1c7', '#3c3836', '#076678', '#79740e', '#cc241d', '#8f3f71'],
    monacoTheme: 'gruvbox-light',
    monacoThemeData: monacoThemeData('vs', '#fbf1c7', '#3c3836', {
      strings: '#79740e',
      keywords: '#9d0006',
      functions: '#b57614',
      types: '#076678',
      comments: '#928374',
      numbers: '#8f3f71',
      operators: '#af3a03',
      variables: '#3c3836',
    }, {
      'editor.selectionBackground': '#ebdbb2',
      'editor.lineHighlightBackground': '#f2e5bc',
      'editorLineNumber.foreground': '#a89984',
      'editorCursor.foreground': '#3c3836',
    }),
    colors: {
      '--bg-primary': '#fbf1c7',
      '--bg-secondary': '#f2e5bc',
      '--bg-tertiary': '#ebdbb2',
      '--bg-hover': '#ebdbb2',
      '--bg-active': '#d5c4a1',
      '--bg-elevated': '#fbf1c7',
      '--border': '#d5c4a1',
      '--border-bright': '#a89984',
      '--border-focus': '#076678',
      '--text-primary': '#3c3836',
      '--text-secondary': '#504945',
      '--text-muted': '#928374',
      '--accent': '#076678',
      '--accent-blue': '#076678',
      '--accent-green': '#79740e',
      '--accent-orange': '#af3a03',
      '--accent-red': '#9d0006',
      '--accent-purple': '#8f3f71',
      '--accent-yellow': '#b57614',
      '--accent-cyan': '#427b58',
      '--scrollbar-thumb': '#a89984',
      '--scrollbar-track': '#fbf1c7',
    },
  },

  // ---------- Palenight ----------
  {
    id: 'palenight',
    name: 'Palenight',
    type: 'dark',
    author: 'Mattia Astorino',
    tags: ['dark', 'popular', 'material', 'cool', 'pastel'],
    previewColors: ['#292d3e', '#a6accd', '#82aaff', '#c3e88d', '#f07178', '#c792ea'],
    monacoTheme: 'palenight',
    monacoThemeData: monacoThemeData('vs-dark', '#292d3e', '#a6accd', {
      strings: '#c3e88d',
      keywords: '#c792ea',
      functions: '#82aaff',
      types: '#ffcb6b',
      comments: '#676e95',
      numbers: '#f78c6c',
      operators: '#89ddff',
      variables: '#a6accd',
    }, {
      'editor.selectionBackground': '#3c435c',
      'editor.lineHighlightBackground': '#2f3344',
      'editorLineNumber.foreground': '#4e5579',
      'editorCursor.foreground': '#ffcc00',
    }),
    colors: {
      '--bg-primary': '#292d3e',
      '--bg-secondary': '#232636',
      '--bg-tertiary': '#2f3344',
      '--bg-hover': '#32374d',
      '--bg-active': '#3c435c',
      '--bg-elevated': '#2f3344',
      '--border': '#3c435c',
      '--border-bright': '#4e5579',
      '--border-focus': '#82aaff',
      '--text-primary': '#a6accd',
      '--text-secondary': '#8890b0',
      '--text-muted': '#676e95',
      '--accent': '#82aaff',
      '--accent-blue': '#82aaff',
      '--accent-green': '#c3e88d',
      '--accent-orange': '#f78c6c',
      '--accent-red': '#f07178',
      '--accent-purple': '#c792ea',
      '--accent-yellow': '#ffcb6b',
      '--accent-cyan': '#89ddff',
      '--scrollbar-thumb': '#4e5579',
      '--scrollbar-track': '#292d3e',
    },
  },

  // ---------- Ayu Dark ----------
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    type: 'dark',
    author: 'Ike Ku',
    tags: ['dark', 'popular', 'modern', 'warm'],
    previewColors: ['#0b0e14', '#bfbdb6', '#e6b450', '#7fd962', '#d95757', '#d2a6ff'],
    monacoTheme: 'ayu-dark',
    monacoThemeData: monacoThemeData('vs-dark', '#0b0e14', '#bfbdb6', {
      strings: '#aad94c',
      keywords: '#ff8f40',
      functions: '#ffb454',
      types: '#59c2ff',
      comments: '#acb6bf8c',
      numbers: '#d2a6ff',
      operators: '#f29668',
      variables: '#bfbdb6',
    }, {
      'editor.selectionBackground': '#1a1f29',
      'editor.lineHighlightBackground': '#0f1319',
      'editorLineNumber.foreground': '#3d424d',
      'editorCursor.foreground': '#e6b450',
    }),
    colors: {
      '--bg-primary': '#0b0e14',
      '--bg-secondary': '#070a0f',
      '--bg-tertiary': '#0d1017',
      '--bg-hover': '#131721',
      '--bg-active': '#1a1f29',
      '--bg-elevated': '#0f1319',
      '--border': '#1a1f29',
      '--border-bright': '#3d424d',
      '--border-focus': '#e6b450',
      '--text-primary': '#bfbdb6',
      '--text-secondary': '#9b9890',
      '--text-muted': '#636a72',
      '--accent': '#e6b450',
      '--accent-blue': '#59c2ff',
      '--accent-green': '#aad94c',
      '--accent-orange': '#ff8f40',
      '--accent-red': '#d95757',
      '--accent-purple': '#d2a6ff',
      '--accent-yellow': '#e6b450',
      '--accent-cyan': '#95e6cb',
      '--scrollbar-thumb': '#3d424d',
      '--scrollbar-track': '#0b0e14',
    },
  },

  // ---------- Ayu Light ----------
  {
    id: 'ayu-light',
    name: 'Ayu Light',
    type: 'light',
    author: 'Ike Ku',
    tags: ['light', 'popular', 'modern', 'warm', 'clean'],
    previewColors: ['#fcfcfc', '#5c6166', '#ff9940', '#86b300', '#f07171', '#a37acc'],
    monacoTheme: 'ayu-light',
    monacoThemeData: monacoThemeData('vs', '#fcfcfc', '#5c6166', {
      strings: '#86b300',
      keywords: '#fa8d3e',
      functions: '#f2ae49',
      types: '#399ee6',
      comments: '#abb0b6',
      numbers: '#a37acc',
      operators: '#ed9366',
      variables: '#5c6166',
    }, {
      'editor.selectionBackground': '#d1e4f4',
      'editor.lineHighlightBackground': '#f3f3f3',
      'editorLineNumber.foreground': '#b8b4a8',
      'editorCursor.foreground': '#ff9940',
    }),
    colors: {
      '--bg-primary': '#fcfcfc',
      '--bg-secondary': '#f3f4f5',
      '--bg-tertiary': '#f8f9fa',
      '--bg-hover': '#ebeced',
      '--bg-active': '#d8d9da',
      '--bg-elevated': '#fcfcfc',
      '--border': '#d8d8d8',
      '--border-bright': '#b8b4a8',
      '--border-focus': '#ff9940',
      '--text-primary': '#5c6166',
      '--text-secondary': '#787b80',
      '--text-muted': '#abb0b6',
      '--accent': '#ff9940',
      '--accent-blue': '#399ee6',
      '--accent-green': '#86b300',
      '--accent-orange': '#fa8d3e',
      '--accent-red': '#f07171',
      '--accent-purple': '#a37acc',
      '--accent-yellow': '#f2ae49',
      '--accent-cyan': '#4cbf99',
      '--scrollbar-thumb': '#b8b4a8',
      '--scrollbar-track': '#fcfcfc',
    },
  },

  // ---------- Rose Pine ----------
  {
    id: 'rose-pine',
    name: 'Ros\u00e9 Pine',
    type: 'dark',
    author: 'Ros\u00e9 Pine',
    tags: ['dark', 'popular', 'pastel', 'elegant', 'warm'],
    previewColors: ['#191724', '#e0def4', '#c4a7e7', '#9ccfd8', '#eb6f92', '#f6c177'],
    monacoTheme: 'rose-pine',
    monacoThemeData: monacoThemeData('vs-dark', '#191724', '#e0def4', {
      strings: '#f6c177',
      keywords: '#31748f',
      functions: '#ebbcba',
      types: '#9ccfd8',
      comments: '#6e6a86',
      numbers: '#c4a7e7',
      operators: '#31748f',
      variables: '#e0def4',
    }, {
      'editor.selectionBackground': '#2a273f',
      'editor.lineHighlightBackground': '#1f1d2e',
      'editorLineNumber.foreground': '#6e6a86',
      'editorCursor.foreground': '#e0def4',
    }),
    colors: {
      '--bg-primary': '#191724',
      '--bg-secondary': '#1f1d2e',
      '--bg-tertiary': '#1f1d2e',
      '--bg-hover': '#26233a',
      '--bg-active': '#2a273f',
      '--bg-elevated': '#26233a',
      '--border': '#26233a',
      '--border-bright': '#6e6a86',
      '--border-focus': '#c4a7e7',
      '--text-primary': '#e0def4',
      '--text-secondary': '#908caa',
      '--text-muted': '#6e6a86',
      '--accent': '#c4a7e7',
      '--accent-blue': '#31748f',
      '--accent-green': '#9ccfd8',
      '--accent-orange': '#f6c177',
      '--accent-red': '#eb6f92',
      '--accent-purple': '#c4a7e7',
      '--accent-yellow': '#f6c177',
      '--accent-cyan': '#9ccfd8',
      '--scrollbar-thumb': '#6e6a86',
      '--scrollbar-track': '#191724',
    },
  },
]

/** Find a theme by id. Falls back to the first theme (Orion Dark). */
export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0]
}
