// Project Templates - Built-in scaffolding system for common project types

export type TemplateCategory =
  | 'Frontend'
  | 'Backend'
  | 'Full-Stack'
  | 'Desktop'
  | 'Mobile'
  | 'Library'
  | 'Tool';

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  icon: string;
  tags: string[];
  files: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
  postCreateCommands: string[];
}

// ---------------------------------------------------------------------------
// Template Definitions
// ---------------------------------------------------------------------------

const reactViteTemplate: ProjectTemplate = {
  id: 'react-ts-vite',
  name: 'React + TypeScript + Vite',
  description: 'Modern React app with TypeScript, Vite bundler, and ESLint pre-configured.',
  category: 'Frontend',
  icon: 'react',
  tags: ['react', 'typescript', 'vite', 'frontend', 'spa'],
  files: {
    'index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{PROJECT_NAME}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
    'src/main.tsx': `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);`,
    'src/App.tsx': `import { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <h1>{{PROJECT_NAME}}</h1>
      <div className="card">
        <button onClick={() => setCount((c) => c + 1)}>
          count is {count}
        </button>
        <p>Edit <code>src/App.tsx</code> and save to test HMR.</p>
      </div>
    </div>
  );
}

export default App;`,
    'src/App.css': `.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.card {
  padding: 2em;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  color: #fff;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #646cff;
}`,
    'src/index.css': `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color: #213547;
  background-color: #ffffff;
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
}`,
    'src/vite-env.d.ts': '/// <reference types="vite/client" />\n',
    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}`,
    'vite.config.ts': `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});`,
    '.gitignore': `node_modules
dist
dist-ssr
*.local
.env
.env.*
`,
  },
  dependencies: {
    react: '^18.3.1',
    'react-dom': '^18.3.1',
  },
  devDependencies: {
    '@types/react': '^18.3.3',
    '@types/react-dom': '^18.3.0',
    '@vitejs/plugin-react': '^4.3.1',
    typescript: '^5.5.3',
    vite: '^5.4.0',
  },
  scripts: {
    dev: 'vite',
    build: 'tsc && vite build',
    preview: 'vite preview',
    lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0',
  },
  postCreateCommands: ['npm install', 'git init'],
};

const nextjsTemplate: ProjectTemplate = {
  id: 'nextjs-app-router',
  name: 'Next.js App Router',
  description: 'Next.js 14 with the App Router, TypeScript, and Tailwind CSS.',
  category: 'Full-Stack',
  icon: 'nextjs',
  tags: ['nextjs', 'react', 'typescript', 'ssr', 'fullstack', 'tailwind'],
  files: {
    'app/layout.tsx': `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '{{PROJECT_NAME}}',
  description: 'Generated by {{PROJECT_NAME}}',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
    'app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to {{PROJECT_NAME}}</h1>
      <p className="mt-4 text-lg text-gray-600">
        Get started by editing <code className="font-mono bg-gray-100 p-1 rounded">app/page.tsx</code>
      </p>
    </main>
  );
}`,
    'app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}`,
    'app/api/hello/route.ts': `import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({ message: 'Hello from {{PROJECT_NAME}}!' });
}`,
    'next.config.mjs': `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;`,
    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
    'tailwind.config.ts': `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: { extend: {} },
  plugins: [],
};

export default config;`,
    'postcss.config.mjs': `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;`,
    '.gitignore': `node_modules
.next
out
.env*.local
`,
  },
  dependencies: {
    next: '^14.2.5',
    react: '^18.3.1',
    'react-dom': '^18.3.1',
  },
  devDependencies: {
    '@types/node': '^20.14.0',
    '@types/react': '^18.3.3',
    '@types/react-dom': '^18.3.0',
    autoprefixer: '^10.4.19',
    postcss: '^8.4.39',
    tailwindcss: '^3.4.6',
    typescript: '^5.5.3',
  },
  scripts: {
    dev: 'next dev',
    build: 'next build',
    start: 'next start',
    lint: 'next lint',
  },
  postCreateCommands: ['npm install', 'git init'],
};

const expressTemplate: ProjectTemplate = {
  id: 'express-api',
  name: 'Express.js API',
  description: 'REST API with Express, TypeScript, and structured middleware.',
  category: 'Backend',
  icon: 'express',
  tags: ['express', 'typescript', 'api', 'rest', 'backend', 'node'],
  files: {
    'src/index.ts': `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { router as apiRouter } from './routes';
import { errorHandler } from './middleware/errorHandler';
import { requestLogger } from './middleware/requestLogger';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(requestLogger);

app.use('/api', apiRouter);

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

app.use(errorHandler);

app.listen(PORT, () => {
  console.log(\`[{{PROJECT_NAME}}] Server running on http://localhost:\${PORT}\`);
});

export default app;`,
    'src/routes/index.ts': `import { Router } from 'express';

export const router = Router();

router.get('/', (_req, res) => {
  res.json({ message: 'Welcome to {{PROJECT_NAME}} API' });
});

router.get('/users', (_req, res) => {
  res.json([
    { id: 1, name: 'Alice' },
    { id: 2, name: 'Bob' },
  ]);
});`,
    'src/middleware/errorHandler.ts': `import { Request, Response, NextFunction } from 'express';

export function errorHandler(
  err: Error,
  _req: Request,
  res: Response,
  _next: NextFunction,
) {
  console.error('[Error]', err.message);
  res.status(500).json({
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : undefined,
  });
}`,
    'src/middleware/requestLogger.ts': `import { Request, Response, NextFunction } from 'express';

export function requestLogger(req: Request, _res: Response, next: NextFunction) {
  const timestamp = new Date().toISOString();
  console.log(\`[\${timestamp}] \${req.method} \${req.url}\`);
  next();
}`,
    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist"]
}`,
    '.env.example': `PORT=3000
NODE_ENV=development
`,
    '.gitignore': `node_modules
dist
.env
*.log
`,
  },
  dependencies: {
    express: '^4.19.2',
    cors: '^2.8.5',
    helmet: '^7.1.0',
    dotenv: '^16.4.5',
  },
  devDependencies: {
    '@types/express': '^4.17.21',
    '@types/cors': '^2.8.17',
    '@types/node': '^20.14.0',
    typescript: '^5.5.3',
    'ts-node-dev': '^2.0.0',
  },
  scripts: {
    dev: 'ts-node-dev --respawn --transpile-only src/index.ts',
    build: 'tsc',
    start: 'node dist/index.js',
    lint: 'eslint src --ext .ts',
  },
  postCreateCommands: ['npm install', 'cp .env.example .env', 'git init'],
};

const fastApiTemplate: ProjectTemplate = {
  id: 'python-fastapi',
  name: 'Python FastAPI',
  description: 'High-performance Python API with FastAPI, Pydantic, and uvicorn.',
  category: 'Backend',
  icon: 'python',
  tags: ['python', 'fastapi', 'api', 'rest', 'async', 'backend'],
  files: {
    'app/main.py': `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routers import items, users

app = FastAPI(
    title="{{PROJECT_NAME}}",
    description="API built with FastAPI",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(users.router, prefix="/api/users", tags=["users"])
app.include_router(items.router, prefix="/api/items", tags=["items"])


@app.get("/")
async def root():
    return {"message": "Welcome to {{PROJECT_NAME}}"}


@app.get("/health")
async def health_check():
    return {"status": "healthy"}`,
    'app/__init__.py': '',
    'app/routers/__init__.py': '',
    'app/routers/users.py': `from fastapi import APIRouter, HTTPException
from app.models import User, UserCreate

router = APIRouter()

fake_db: list[User] = [
    User(id=1, name="Alice", email="alice@example.com"),
    User(id=2, name="Bob", email="bob@example.com"),
]


@router.get("/", response_model=list[User])
async def list_users():
    return fake_db


@router.get("/{user_id}", response_model=User)
async def get_user(user_id: int):
    for user in fake_db:
        if user.id == user_id:
            return user
    raise HTTPException(status_code=404, detail="User not found")


@router.post("/", response_model=User, status_code=201)
async def create_user(payload: UserCreate):
    new_id = max((u.id for u in fake_db), default=0) + 1
    user = User(id=new_id, **payload.model_dump())
    fake_db.append(user)
    return user`,
    'app/routers/items.py': `from fastapi import APIRouter

router = APIRouter()


@router.get("/")
async def list_items():
    return [{"id": 1, "name": "Widget", "price": 9.99}]`,
    'app/models.py': `from pydantic import BaseModel, EmailStr


class UserCreate(BaseModel):
    name: str
    email: str


class User(BaseModel):
    id: int
    name: str
    email: str`,
    'requirements.txt': `fastapi>=0.111.0
uvicorn[standard]>=0.30.0
pydantic>=2.7.0
python-dotenv>=1.0.0
`,
    'pyproject.toml': `[project]
name = "{{PROJECT_NAME}}"
version = "0.1.0"
description = "A FastAPI project"
requires-python = ">=3.11"

[tool.ruff]
line-length = 100
target-version = "py311"`,
    '.gitignore': `__pycache__
*.pyc
.venv
.env
*.egg-info
dist
`,
  },
  dependencies: {},
  devDependencies: {},
  scripts: {
    dev: 'uvicorn app.main:app --reload --port 8000',
    start: 'uvicorn app.main:app --host 0.0.0.0 --port 8000',
    test: 'pytest',
  },
  postCreateCommands: [
    'python -m venv .venv',
    '.venv/bin/pip install -r requirements.txt',
    'git init',
  ],
};

const electronTemplate: ProjectTemplate = {
  id: 'electron-app',
  name: 'Electron App',
  description: 'Cross-platform desktop application with Electron, TypeScript, and a React renderer.',
  category: 'Desktop',
  icon: 'electron',
  tags: ['electron', 'desktop', 'typescript', 'react', 'cross-platform'],
  files: {
    'src/main/index.ts': `import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'node:path';

let mainWindow: BrowserWindow | null = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  if (process.env.VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL);
    mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, '../renderer/index.html'));
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

ipcMain.handle('get-app-version', () => app.getVersion());`,
    'src/preload/index.ts': `import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  getVersion: () => ipcRenderer.invoke('get-app-version'),
});`,
    'src/renderer/index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{PROJECT_NAME}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.tsx"></script>
  </body>
</html>`,
    'src/renderer/main.tsx': `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);`,
    'src/renderer/App.tsx': `import { useEffect, useState } from 'react';

declare global {
  interface Window {
    electronAPI: {
      getVersion: () => Promise<string>;
    };
  }
}

export default function App() {
  const [version, setVersion] = useState('');

  useEffect(() => {
    window.electronAPI.getVersion().then(setVersion);
  }, []);

  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>{{PROJECT_NAME}}</h1>
      <p>Electron version: {version}</p>
      <p>Edit <code>src/renderer/App.tsx</code> to get started.</p>
    </div>
  );
}`,
    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "dist"
  },
  "include": ["src"]
}`,
    '.gitignore': `node_modules
dist
out
.env
`,
  },
  dependencies: {
    react: '^18.3.1',
    'react-dom': '^18.3.1',
  },
  devDependencies: {
    electron: '^31.2.0',
    '@types/react': '^18.3.3',
    '@types/react-dom': '^18.3.0',
    typescript: '^5.5.3',
    vite: '^5.4.0',
    '@vitejs/plugin-react': '^4.3.1',
  },
  scripts: {
    dev: 'vite',
    build: 'tsc && vite build',
    'electron:dev': 'electron .',
    'electron:build': 'electron-builder',
  },
  postCreateCommands: ['npm install', 'git init'],
};

// ---------------------------------------------------------------------------
// Lightweight templates (metadata + minimal files)
// ---------------------------------------------------------------------------

const fastifyTemplate: ProjectTemplate = {
  id: 'fastify-api',
  name: 'Fastify API',
  description: 'Blazing-fast REST API with Fastify and TypeScript.',
  category: 'Backend',
  icon: 'fastify',
  tags: ['fastify', 'typescript', 'api', 'rest', 'backend', 'node'],
  files: {
    'src/index.ts': `import Fastify from 'fastify';

const server = Fastify({ logger: true });

server.get('/', async () => ({ hello: '{{PROJECT_NAME}}' }));

server.listen({ port: 3000, host: '0.0.0.0' }, (err) => {
  if (err) { server.log.error(err); process.exit(1); }
});`,
  },
  dependencies: { fastify: '^4.28.0' },
  devDependencies: { typescript: '^5.5.3', '@types/node': '^20.14.0', 'ts-node-dev': '^2.0.0' },
  scripts: { dev: 'ts-node-dev --respawn src/index.ts', build: 'tsc', start: 'node dist/index.js' },
  postCreateCommands: ['npm install', 'git init'],
};

const flaskTemplate: ProjectTemplate = {
  id: 'python-flask',
  name: 'Python Flask',
  description: 'Lightweight Python web framework with Flask.',
  category: 'Backend',
  icon: 'python',
  tags: ['python', 'flask', 'api', 'backend', 'web'],
  files: {
    'app.py': `from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/")
def index():
    return jsonify(message="Welcome to {{PROJECT_NAME}}")


@app.route("/health")
def health():
    return jsonify(status="ok")


if __name__ == "__main__":
    app.run(debug=True)`,
    'requirements.txt': 'flask>=3.0.0\npython-dotenv>=1.0.0\n',
    '.gitignore': '__pycache__\n*.pyc\n.venv\n.env\n',
  },
  dependencies: {},
  devDependencies: {},
  scripts: { dev: 'flask run --debug', start: 'flask run' },
  postCreateCommands: ['python -m venv .venv', '.venv/bin/pip install -r requirements.txt', 'git init'],
};

const rustCargoTemplate: ProjectTemplate = {
  id: 'rust-cargo',
  name: 'Rust Cargo',
  description: 'Rust project scaffolded with Cargo.',
  category: 'Tool',
  icon: 'rust',
  tags: ['rust', 'cargo', 'systems', 'cli'],
  files: {
    'src/main.rs': `fn main() {\n    println!("Hello from {{PROJECT_NAME}}!");\n}`,
    'Cargo.toml': `[package]\nname = "{{PROJECT_NAME}}"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n`,
    '.gitignore': '/target\n',
  },
  dependencies: {},
  devDependencies: {},
  scripts: { build: 'cargo build', run: 'cargo run', test: 'cargo test' },
  postCreateCommands: ['cargo build', 'git init'],
};

const goModuleTemplate: ProjectTemplate = {
  id: 'go-module',
  name: 'Go Module',
  description: 'Go project with module initialization and a simple HTTP server.',
  category: 'Backend',
  icon: 'go',
  tags: ['go', 'golang', 'api', 'backend'],
  files: {
    'main.go': `package main

import (
\t"fmt"
\t"log"
\t"net/http"
)

func main() {
\thttp.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
\t\tfmt.Fprintf(w, "Hello from {{PROJECT_NAME}}!")
\t})
\tlog.Println("Listening on :8080")
\tlog.Fatal(http.ListenAndServe(":8080", nil))
}`,
    'go.mod': `module {{PROJECT_NAME}}\n\ngo 1.22\n`,
    '.gitignore': 'bin/\n*.exe\n',
  },
  dependencies: {},
  devDependencies: {},
  scripts: { run: 'go run .', build: 'go build -o bin/app', test: 'go test ./...' },
  postCreateCommands: ['git init'],
};

const vue3ViteTemplate: ProjectTemplate = {
  id: 'vue3-vite',
  name: 'Vue 3 + Vite',
  description: 'Vue 3 with Composition API, TypeScript, and Vite.',
  category: 'Frontend',
  icon: 'vue',
  tags: ['vue', 'vue3', 'typescript', 'vite', 'frontend'],
  files: {
    'src/App.vue': `<script setup lang="ts">
import { ref } from 'vue';
const count = ref(0);
</script>

<template>
  <h1>{{PROJECT_NAME}}</h1>
  <button @click="count++">Count: {{ count }}</button>
</template>`,
    'src/main.ts': `import { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).mount('#app');\n`,
    'index.html': `<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8" /><title>{{PROJECT_NAME}}</title></head>\n<body><div id="app"></div><script type="module" src="/src/main.ts"></script></body></html>`,
    'vite.config.ts': `import { defineConfig } from 'vite';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({ plugins: [vue()] });\n`,
    'tsconfig.json': `{\n  "compilerOptions": { "target": "ES2020", "module": "ESNext", "moduleResolution": "bundler", "strict": true, "jsx": "preserve", "skipLibCheck": true },\n  "include": ["src"]\n}`,
    '.gitignore': 'node_modules\ndist\n',
  },
  dependencies: { vue: '^3.4.31' },
  devDependencies: { '@vitejs/plugin-vue': '^5.0.5', typescript: '^5.5.3', vite: '^5.4.0' },
  scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
  postCreateCommands: ['npm install', 'git init'],
};

const svelteKitTemplate: ProjectTemplate = {
  id: 'sveltekit',
  name: 'SvelteKit',
  description: 'Full-stack Svelte framework with routing and SSR.',
  category: 'Full-Stack',
  icon: 'svelte',
  tags: ['svelte', 'sveltekit', 'typescript', 'ssr', 'fullstack'],
  files: {
    'src/routes/+page.svelte': `<h1>Welcome to {{PROJECT_NAME}}</h1>\n<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation.</p>`,
    'src/app.html': `<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" />%sveltekit.head%</head><body data-sveltekit-preload-data="hover">%sveltekit.body%</body></html>`,
    'svelte.config.js': `import adapter from '@sveltejs/adapter-auto';\nexport default { kit: { adapter: adapter() } };\n`,
    '.gitignore': 'node_modules\n.svelte-kit\nbuild\n',
  },
  dependencies: {},
  devDependencies: { '@sveltejs/adapter-auto': '^3.2.2', '@sveltejs/kit': '^2.5.18', svelte: '^4.2.18', typescript: '^5.5.3', vite: '^5.4.0' },
  scripts: { dev: 'vite dev', build: 'vite build', preview: 'vite preview' },
  postCreateCommands: ['npm install', 'git init'],
};

const tailwindStarterTemplate: ProjectTemplate = {
  id: 'tailwind-starter',
  name: 'Tailwind CSS Starter',
  description: 'Plain HTML + Tailwind CSS for rapid prototyping.',
  category: 'Frontend',
  icon: 'tailwind',
  tags: ['tailwind', 'css', 'html', 'frontend', 'prototype'],
  files: {
    'src/input.css': '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n',
    'index.html': `<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><link href="dist/output.css" rel="stylesheet" /><title>{{PROJECT_NAME}}</title></head>\n<body class="min-h-screen bg-gray-50 flex items-center justify-center"><h1 class="text-4xl font-bold text-blue-600">{{PROJECT_NAME}}</h1></body></html>`,
    'tailwind.config.js': `/** @type {import('tailwindcss').Config} */\nmodule.exports = { content: ["./**/*.html"], theme: { extend: {} }, plugins: [] };\n`,
    '.gitignore': 'node_modules\ndist\n',
  },
  dependencies: {},
  devDependencies: { tailwindcss: '^3.4.6' },
  scripts: { dev: 'npx tailwindcss -i src/input.css -o dist/output.css --watch', build: 'npx tailwindcss -i src/input.css -o dist/output.css --minify' },
  postCreateCommands: ['npm install', 'git init'],
};

const turborepoTemplate: ProjectTemplate = {
  id: 'monorepo-turborepo',
  name: 'Monorepo (Turborepo)',
  description: 'Turborepo monorepo with shared packages and multiple apps.',
  category: 'Tool',
  icon: 'turborepo',
  tags: ['monorepo', 'turborepo', 'typescript', 'workspace'],
  files: {
    'turbo.json': `{\n  "$schema": "https://turbo.build/schema.json",\n  "pipeline": {\n    "build": { "dependsOn": ["^build"], "outputs": ["dist/**"] },\n    "dev": { "cache": false, "persistent": true },\n    "lint": {}\n  }\n}`,
    'package.json': `{\n  "name": "{{PROJECT_NAME}}",\n  "private": true,\n  "workspaces": ["apps/*", "packages/*"]\n}`,
    'apps/web/package.json': `{\n  "name": "@{{PROJECT_NAME}}/web",\n  "version": "0.0.0",\n  "private": true,\n  "scripts": { "dev": "echo web dev" }\n}`,
    'packages/shared/package.json': `{\n  "name": "@{{PROJECT_NAME}}/shared",\n  "version": "0.0.0",\n  "main": "src/index.ts"\n}`,
    'packages/shared/src/index.ts': `export const APP_NAME = '{{PROJECT_NAME}}';\n`,
    '.gitignore': 'node_modules\ndist\n.turbo\n',
  },
  dependencies: {},
  devDependencies: { turbo: '^2.0.6' },
  scripts: { dev: 'turbo dev', build: 'turbo build', lint: 'turbo lint' },
  postCreateCommands: ['npm install', 'git init'],
};

const chromeExtTemplate: ProjectTemplate = {
  id: 'chrome-extension',
  name: 'Chrome Extension',
  description: 'Manifest V3 Chrome extension with popup and background script.',
  category: 'Tool',
  icon: 'chrome',
  tags: ['chrome', 'extension', 'browser', 'javascript'],
  files: {
    'manifest.json': `{\n  "manifest_version": 3,\n  "name": "{{PROJECT_NAME}}",\n  "version": "1.0.0",\n  "description": "A Chrome extension",\n  "action": { "default_popup": "popup.html", "default_icon": "icon.png" },\n  "background": { "service_worker": "background.js" },\n  "permissions": ["storage"]\n}`,
    'popup.html': `<!DOCTYPE html>\n<html><head><style>body{width:300px;padding:16px;font-family:system-ui}</style></head>\n<body><h1>{{PROJECT_NAME}}</h1><p id="msg">Loading...</p><script src="popup.js"></script></body></html>`,
    'popup.js': `document.getElementById('msg').textContent = 'Extension loaded!';`,
    'background.js': `chrome.runtime.onInstalled.addListener(() => {\n  console.log('{{PROJECT_NAME}} installed');\n});`,
    '.gitignore': 'node_modules\ndist\n',
  },
  dependencies: {},
  devDependencies: {},
  scripts: {},
  postCreateCommands: ['git init'],
};

const cliToolTemplate: ProjectTemplate = {
  id: 'cli-tool-node',
  name: 'CLI Tool (Node.js)',
  description: 'Command-line tool with argument parsing and coloured output.',
  category: 'Tool',
  icon: 'terminal',
  tags: ['cli', 'node', 'typescript', 'tool', 'terminal'],
  files: {
    'src/index.ts': `#!/usr/bin/env node

import { parseArgs } from 'node:util';

const { values } = parseArgs({
  options: {
    name: { type: 'string', short: 'n', default: 'World' },
    verbose: { type: 'boolean', short: 'v', default: false },
  },
});

console.log(\`Hello, \${values.name}!\`);
if (values.verbose) {
  console.log('Running in verbose mode.');
}`,
    'tsconfig.json': `{\n  "compilerOptions": { "target": "ES2022", "module": "NodeNext", "moduleResolution": "NodeNext", "outDir": "dist", "rootDir": "src", "strict": true, "esModuleInterop": true, "skipLibCheck": true },\n  "include": ["src"]\n}`,
    'package.json': `{\n  "name": "{{PROJECT_NAME}}",\n  "version": "0.1.0",\n  "bin": { "{{PROJECT_NAME}}": "dist/index.js" },\n  "type": "module"\n}`,
    '.gitignore': 'node_modules\ndist\n',
  },
  dependencies: {},
  devDependencies: { typescript: '^5.5.3', '@types/node': '^20.14.0' },
  scripts: { build: 'tsc', dev: 'ts-node-dev src/index.ts', prepublishOnly: 'npm run build' },
  postCreateCommands: ['npm install', 'git init'],
};

// ---------------------------------------------------------------------------
// Template Registry
// ---------------------------------------------------------------------------

const ALL_TEMPLATES: ProjectTemplate[] = [
  reactViteTemplate,
  nextjsTemplate,
  expressTemplate,
  fastApiTemplate,
  electronTemplate,
  fastifyTemplate,
  flaskTemplate,
  rustCargoTemplate,
  goModuleTemplate,
  vue3ViteTemplate,
  svelteKitTemplate,
  tailwindStarterTemplate,
  turborepoTemplate,
  chromeExtTemplate,
  cliToolTemplate,
];

const POPULAR_IDS = new Set([
  'react-ts-vite',
  'nextjs-app-router',
  'express-api',
  'python-fastapi',
  'vue3-vite',
]);

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns every registered project template.
 */
export function getTemplates(): ProjectTemplate[] {
  return [...ALL_TEMPLATES];
}

/**
 * Looks up a single template by its unique `id`.
 */
export function getTemplateById(id: string): ProjectTemplate | undefined {
  return ALL_TEMPLATES.find((t) => t.id === id);
}

/**
 * Search and filter templates by a free-text query and/or category.
 *
 * The query is matched case-insensitively against the template name,
 * description, and tags.  If a category is provided it must match exactly
 * (case-insensitive).
 */
export function filterTemplates(
  query: string,
  category?: TemplateCategory | string,
): ProjectTemplate[] {
  const q = query.toLowerCase().trim();

  return ALL_TEMPLATES.filter((t) => {
    // Category gate
    if (category && t.category.toLowerCase() !== category.toLowerCase()) {
      return false;
    }

    // Empty query matches everything within the category
    if (q === '') return true;

    // Check name, description, and tags
    if (t.name.toLowerCase().includes(q)) return true;
    if (t.description.toLowerCase().includes(q)) return true;
    if (t.tags.some((tag) => tag.toLowerCase().includes(q))) return true;

    // Support multi-word queries — all terms must match somewhere
    const terms = q.split(/\s+/);
    if (terms.length > 1) {
      const blob = `${t.name} ${t.description} ${t.tags.join(' ')}`.toLowerCase();
      return terms.every((term) => blob.includes(term));
    }

    return false;
  });
}

/**
 * Returns the most popular / recommended templates.
 */
export function getPopularTemplates(): ProjectTemplate[] {
  return ALL_TEMPLATES.filter((t) => POPULAR_IDS.has(t.id));
}

/**
 * Generates the final file map for a project by replacing the
 * `{{PROJECT_NAME}}` placeholder in every file path and content string.
 *
 * Also synthesises a `package.json` (for Node-based templates) that merges
 * the template's dependencies, devDependencies, and scripts.
 */
export function generateProjectFiles(
  template: ProjectTemplate,
  projectName: string,
): Record<string, string> {
  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '-').toLowerCase();
  const result: Record<string, string> = {};

  // Copy and interpolate template files
  for (const [filePath, content] of Object.entries(template.files)) {
    const resolvedPath = filePath.replace(/\{\{PROJECT_NAME\}\}/g, safeName);
    result[resolvedPath] = content.replace(/\{\{PROJECT_NAME\}\}/g, safeName);
  }

  // Generate a package.json for Node-based templates when one isn't already
  // provided explicitly in the file map.
  const hasNodeDeps =
    Object.keys(template.dependencies).length > 0 ||
    Object.keys(template.devDependencies).length > 0;

  if (hasNodeDeps && !result['package.json']) {
    const pkg: Record<string, unknown> = {
      name: safeName,
      version: '0.1.0',
      private: true,
      scripts: template.scripts,
      dependencies: template.dependencies,
      devDependencies: template.devDependencies,
    };
    result['package.json'] = JSON.stringify(pkg, null, 2) + '\n';
  }

  // If a package.json already exists in files, merge deps/scripts into it
  if (hasNodeDeps && template.files['package.json']) {
    try {
      const existing = JSON.parse(result['package.json']);
      existing.dependencies = { ...existing.dependencies, ...template.dependencies };
      existing.devDependencies = { ...existing.devDependencies, ...template.devDependencies };
      existing.scripts = { ...existing.scripts, ...template.scripts };
      result['package.json'] = JSON.stringify(existing, null, 2) + '\n';
    } catch {
      // If parsing fails, leave as-is
    }
  }

  return result;
}
